export enum ProductType {
    api = 'api',
    sms = 'sms',
    bitrix = 'crm-bitrix',
    alfacrm = 'crm-alfa',
    amocrm = 'crm-amocrm',
    customcrm = 'crm-custom',
    callingTts = 'calling-tts',
    telegram = 'telegram',
    sm = 'smart-routing',
    tts = 'tts',
    stt = 'stt',
    analitic = 'analitic',
    cqa = 'cqa',
    missedCall = 'missed-call',
}
