import {
    BaseEventData,
    HangupEventData,
    NewchannelEventData,
    OutboundRegistrationDetailEventData,
    RegistryEventData,
    VarSetEventData,
} from './ami.interface';

export enum AsteriskEventType {
    AGIExecEnd = 'AGIExecEnd',
    AGIExecStart = 'AGIExecStart',
    AOC_D = 'AOC-D',
    AOC_E = 'AOC-E',
    AOC_S = 'AOC-S',
    AgentCalled = 'AgentCalled',
    AgentComplete = 'AgentComplete',
    AgentConnect = 'AgentConnect',
    AgentDump = 'AgentDump',
    AgentLogin = 'AgentLogin',
    AgentLogoff = 'AgentLogoff',
    AgentRingNoAnswer = 'AgentRingNoAnswer',
    Agents = 'Agents',
    AgentsComplete = 'AgentsComplete',
    Alarm = 'Alarm',
    AlarmClear = 'AlarmClear',
    AorDetail = 'AorDetail',
    AorList = 'AorList',
    AorListComplete = 'AorListComplete',
    AsyncAGIEnd = 'AsyncAGIEnd',
    AsyncAGIExec = 'AsyncAGIExec',
    AsyncAGIStart = 'AsyncAGIStart',
    AttendedTransfer = 'AttendedTransfer',
    AuthDetail = 'AuthDetail',
    AuthList = 'AuthList',
    AuthListComplete = 'AuthListComplete',
    AuthMethodNotAllowed = 'AuthMethodNotAllowed',
    BlindTransfer = 'BlindTransfer',
    BridgeCreate = 'BridgeCreate',
    BridgeDestroy = 'BridgeDestroy',
    BridgeEnter = 'BridgeEnter',
    BridgeInfoChannel = 'BridgeInfoChannel',
    BridgeInfoComplete = 'BridgeInfoComplete',
    BridgeLeave = 'BridgeLeave',
    BridgeMerge = 'BridgeMerge',
    BridgeVideoSourceUpdate = 'BridgeVideoSourceUpdate',
    CEL = 'CEL',
    Cdr = 'Cdr',
    ChallengeResponseFailed = 'ChallengeResponseFailed',
    ChallengeSent = 'ChallengeSent',
    ChanSpyStart = 'ChanSpyStart',
    ChanSpyStop = 'ChanSpyStop',
    ChannelTalkingStart = 'ChannelTalkingStart',
    ChannelTalkingStop = 'ChannelTalkingStop',
    ConfbridgeEnd = 'ConfbridgeEnd',
    ConfbridgeJoin = 'ConfbridgeJoin',
    ConfbridgeLeave = 'ConfbridgeLeave',
    ConfbridgeList = 'ConfbridgeList',
    ConfbridgeListRooms = 'ConfbridgeListRooms',
    ConfbridgeMute = 'ConfbridgeMute',
    ConfbridgeRecord = 'ConfbridgeRecord',
    ConfbridgeStart = 'ConfbridgeStart',
    ConfbridgeStopRecord = 'ConfbridgeStopRecord',
    ConfbridgeTalking = 'ConfbridgeTalking',
    ConfbridgeUnmute = 'ConfbridgeUnmute',
    ContactList = 'ContactList',
    ContactListComplete = 'ContactListComplete',
    ContactStatus = 'ContactStatus',
    ContactStatusDetail = 'ContactStatusDetail',
    CoreShowChannel = 'CoreShowChannel',
    CoreShowChannelMapComplete = 'CoreShowChannelMapComplete',
    CoreShowChannelsComplete = 'CoreShowChannelsComplete',
    DAHDIChannel = 'DAHDIChannel',
    DNDState = 'DNDState',
    DTMFBegin = 'DTMFBegin',
    DTMFEnd = 'DTMFEnd',
    DeadlockStart = 'DeadlockStart',
    DeviceStateChange = 'DeviceStateChange',
    DeviceStateListComplete = 'DeviceStateListComplete',
    DialBegin = 'DialBegin',
    DialEnd = 'DialEnd',
    DialState = 'DialState',
    EndpointDetail = 'EndpointDetail',
    EndpointDetailComplete = 'EndpointDetailComplete',
    EndpointList = 'EndpointList',
    EndpointListComplete = 'EndpointListComplete',
    ExtensionStateListComplete = 'ExtensionStateListComplete',
    ExtensionStatus = 'ExtensionStatus',
    FAXSession = 'FAXSession',
    FAXSessionsComplete = 'FAXSessionsComplete',
    FAXSessionsEntry = 'FAXSessionsEntry',
    FAXStats = 'FAXStats',
    FAXStatus = 'FAXStatus',
    FailedACL = 'FailedACL',
    Flash = 'Flash',
    FullyBooted = 'FullyBooted',
    Hangup = 'Hangup',
    HangupHandlerPop = 'HangupHandlerPop',
    HangupHandlerPush = 'HangupHandlerPush',
    HangupHandlerRun = 'HangupHandlerRun',
    HangupRequest = 'HangupRequest',
    Hold = 'Hold',
    IdentifyDetail = 'IdentifyDetail',
    InvalidAccountID = 'InvalidAccountID',
    InvalidPassword = 'InvalidPassword',
    InvalidTransport = 'InvalidTransport',
    Load = 'Load',
    LoadAverageLimit = 'LoadAverageLimit',
    LocalBridge = 'LocalBridge',
    LocalOptimizationBegin = 'LocalOptimizationBegin',
    LocalOptimizationEnd = 'LocalOptimizationEnd',
    LogChannel = 'LogChannel',
    MCID = 'MCID',
    MWIGet = 'MWIGet',
    MWIGetComplete = 'MWIGetComplete',
    MeetmeEnd = 'MeetmeEnd',
    MeetmeJoin = 'MeetmeJoin',
    MeetmeLeave = 'MeetmeLeave',
    MeetmeList = 'MeetmeList',
    MeetmeListRooms = 'MeetmeListRooms',
    MeetmeMute = 'MeetmeMute',
    MeetmeTalkRequest = 'MeetmeTalkRequest',
    MeetmeTalking = 'MeetmeTalking',
    MemoryLimit = 'MemoryLimit',
    MessageWaiting = 'MessageWaiting',
    MiniVoiceMail = 'MiniVoiceMail',
    MixMonitorMute = 'MixMonitorMute',
    MixMonitorStart = 'MixMonitorStart',
    MixMonitorStop = 'MixMonitorStop',
    MonitorStart = 'MonitorStart',
    MonitorStop = 'MonitorStop',
    MusicOnHoldStart = 'MusicOnHoldStart',
    MusicOnHoldStop = 'MusicOnHoldStop',
    NewAccountCode = 'NewAccountCode',
    NewCallerid = 'NewCallerid',
    NewConnectedLine = 'NewConnectedLine',
    NewExten = 'NewExten',
    Newchannel = 'NewChannel',
    Newstate = 'Newstate',
    OriginateResponse = 'OriginateResponse',
    ParkedCall = 'ParkedCall',
    ParkedCallGiveUp = 'ParkedCallGiveUp',
    ParkedCallSwap = 'ParkedCallSwap',
    ParkedCallTimeOut = 'ParkedCallTimeOut',
    PeerStatus = 'PeerStatus',
    Pickup = 'Pickup',
    PresenceStateChange = 'PresenceStateChange',
    PresenceStateListComplete = 'PresenceStateListComplete',
    PresenceStatus = 'PresenceStatus',
    QueueCallerAbandon = 'QueueCallerAbandon',
    QueueCallerJoin = 'QueueCallerJoin',
    QueueCallerLeave = 'QueueCallerLeave',
    QueueEntry = 'QueueEntry',
    QueueMemberAdded = 'QueueMemberAdded',
    QueueMemberPause = 'QueueMemberPause',
    QueueMemberPenalty = 'QueueMemberPenalty',
    QueueMemberRemoved = 'QueueMemberRemoved',
    QueueMemberRinginuse = 'QueueMemberRinginuse',
    QueueMemberStatus = 'QueueMemberStatus',
    QueueParams = 'QueueParams',
    RTCPReceived = 'RTCPReceived',
    RTCPSent = 'RTCPSent',
    ReceiveFAX = 'ReceiveFAX',
    Registry = 'Registry',
    Reload = 'Reload',
    Rename = 'Rename',
    RequestBadFormat = 'RequestBadFormat',
    RequestNotAllowed = 'RequestNotAllowed',
    RequestNotSupported = 'RequestNotSupported',
    SIPQualifyPeerDone = 'SIPQualifyPeerDone',
    SendFAX = 'SendFAX',
    SessionLimit = 'SessionLimit',
    SessionTimeout = 'SessionTimeout',
    Shutdown = 'Shutdown',
    SoftHangupRequest = 'SoftHangupRequest',
    SpanAlarm = 'SpanAlarm',
    SpanAlarmClear = 'SpanAlarmClear',
    Status = 'Status',
    StatusComplete = 'StatusComplete',
    SuccessfulAuth = 'SuccessfulAuth',
    TransportDetail = 'TransportDetail',
    UnParkedCall = 'UnParkedCall',
    UnexpectedAddress = 'UnexpectedAddress',
    Unhold = 'Unhold',
    Unload = 'Unload',
    UserEvent = 'UserEvent',
    VarSet = 'VarSet',
    VoicemailPasswordChange = 'VoicemailPasswordChange',
    Wink = 'Wink',
    OutboundRegistrationDetail = 'OutboundRegistrationDetail',
}

export enum RegisterStatus {
    Registered = 'Registered',
    Unregistered = 'Unregistered',
    Rejected = 'Rejected',
    Failed = 'Failed',
}

export enum ChannelStateDesc {
    Down = 'Down',
    Rsrvd = 'Rsrvd',
    OffHook = 'OffHook',
    Dialing = 'Dialing',
    Ring = 'Ring',
    Ringing = 'Ringing',
    Up = 'Up',
    Busy = 'Busy',
    Dialing_Offhook = 'Dialing Offhook',
    Pre_ring = 'Pre-ring',
    Unknown = 'Unknown',
}

export type AsteriskUnionEventData =
    | RegistryEventData
    | VarSetEventData
    | NewchannelEventData
    | HangupEventData
    | BaseEventData
    | OutboundRegistrationDetailEventData;

export enum ActionResult {
    Success = 'Success',
}
